# Write a sample dockerfile to run this Hello World Rust application
# The application is a simple command line program that prints "Hello, Docker!" to the console
# Use multi-stage builds to keep the final image small


# Look at demo/Dockerfile.production for reference

FROM rust:latest AS builder
