# Docker Compose file for running a Minecraft server
# This file defines how to run the Minecraft server container

services:  # List of services (containers) to run
  mc:  # Name of the service - you can reference it with 'docker compose logs mc'
    image: itzg/minecraft-server  # The Docker image to use from Docker Hub
    tty: true  # Allocate a pseudo-TTY (allows interactive terminal)
    stdin_open: true  # Keep STDIN open (allows you to type server commands)
    ports:  # Maps ports from host machine to container
      - "25565:25566"  # Format: "host_port:container_port"
    environment:  # Environment variables passed to the container
      EULA: "FALSE"  # Must be TRUE to accept Minecraft EULA
      TYPE: "VANILLA"  # The type of Minecraft server (VANILLA, PAPER, FORGE, etc.)
    volumes:  # Mount directories from host to container to persist data
      - ./data:/data  # Stores world data, plugins, configs in ./data folder

# ==========================================
# ERRORS TO FIX:
# ==========================================
# 1. The container port mapping is incorrect - Minecraft servers run on port 25565
#    inside the container, not 25566. Fix the ports section.
#
# 2. The EULA environment variable must be set to "TRUE" to accept the Minecraft
#    End User License Agreement, otherwise the server won't start.
#
# Once fixed, run: docker compose up -d
# To view logs: docker compose logs -f mc
# To stop: docker compose down